### ISSUE TITLE
CONTENT - SERVICES - Google Ads: Confirm copy is correct, add edits here.

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#17]

**Comment by jakewelchert** [comment]
Content add/edited and up for review. Images are FPO (for placement only). We'll need to figure out what we want for these. Could be a similar style to the SEO page, or we could go with more of the lightning bolt/textured look.

**Comment by jasonfyve** [comment]
-add H1 badge
-These need to be changed to H2's (not sure the best way to do it so that it doesn't mess with the formatting)
1. What is Pay Per Click Advertising?
2. Right Place. Right Time.

-Make each client name an H3 in the Our Work section
-Is it possible to make the name's of the people in the Fresh Feedback section H5's?
-Uploading the background pictures for the top sections in order.
![WhaIsPPC](https://user-images.githubusercontent.com/77985060/107079782-f14c8f00-67b5-11eb-8156-2a1b8eddcf6d.jpg)
![RightPlaceRightTime](https://user-images.githubusercontent.com/77985060/107079794-f4e01600-67b5-11eb-9df3-03b94c23c6af.jpg)

**Comment by jakewelchert** [comment]
Up for review. Images added. H2's and H3's corrected. 

Moved Fresh Feedback comment to duplicate issue. Started new H1 badge issue.

**Comment by jasonfyve** [comment]
Looks perfect!
