### ISSUE TITLE
CONTENT - SERVICES - Social Media: Confirm copy is correct, add edits here.

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#18]

**Comment by jakewelchert** [comment]
Content add/edited and up for review. Images are FPO (for placement only). We'll need to figure out what we want for these. Could be a similar style to the SEO page, or we could go with more of the lightning bolt/textured look.

**Comment by jasonfyve** [comment]
-add H1 badge
-These need to be changed to H2's (not sure the best way to do it so that it doesn't mess with the formatting)
1. Does Social Media Marketing Work?
2. Why is FYVE the Best?

-Make each client name an H3 in the Our Work section
-Is it possible to make the name's of the people in the Fresh Feedback section H5's?
-Uploading the background pictures for the top sections in order.
![DoesSocialMediaWork](https://user-images.githubusercontent.com/77985060/107084139-45f30880-67bc-11eb-98aa-6484fdfa604d.jpg)
![WhyIsFyveTheBest](https://user-images.githubusercontent.com/77985060/107084333-881c4a00-67bc-11eb-9cbd-3f17a1247b8a.png)

**Comment by jakewelchert** [comment]
Up for review. Images added. Headline changed. H2's and H3's corrected. 

Moved Fresh Feedback comment to duplicate issue. Started new H1 badge issue.

**Comment by jasonfyve** [comment]
Looks perfect!
