### ISSUE TITLE
CONTENT - SERVICES - Content Marketing: Confirm copy is correct, add edits here.

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/fyve#19]

**Comment by jakewelchert** [comment]
Content add/edited and up for review. Images are FPO (for placement only). We'll need to figure out what we want for these. Could be a similar style to the SEO page, or we could go with more of the lightning bolt/textured look.

**Comment by jasonfyve** [comment]
-add H1 badge
-These need to be changed to H2's (not sure the best way to do it so that it doesn't mess with the formatting)
1. What is Email & Content Marketing?

-Make the Our Work section H2 "Using our Email Marketing Powers for Local Columbus Businesses" I forgot to add the word "power" in my content
-Make each client name an H3 in the Our Work section
-Is it possible to make the name's of the people in the Fresh Feedback section H5's?
-Uploading the background pictures for the top sections in order.
![WhatIsContentMarketing](https://user-images.githubusercontent.com/77985060/107085797-98cdbf80-67be-11eb-9be8-8ea624a21a96.jpg)

**Comment by jakewelchert** [comment]
Up for review. Image added. Headline changed. 

Moved Fresh Feedback comment to duplicate issue. Started new H1 badge issue.

**Comment by jasonfyve** [comment]
Looks perfect!
